Bug fixes
narunlifescience/AlphaPlot pull request #21
Opened 2020-10-16 14:58 UTC by filipestevao

I'm using AlphaPlot and I noticed some weird behaviors.

Tested versions: 1.011 and with the last commit ([b8ff430](https://github.com/narunlifescience/AlphaPlot/commit/b8ff4307ae9eb0dced60f266d584bd5532e8c491)).

When the app loads an aproj file:

* if the main window is maximized, it returns to the non-maximized form;
* the Results Log is shown automatically;
* the 2D graph is automatically resized to number 5 if the data starts with a number greater than 5.

To reproduce this last point:

1) create a new table where the data starts with a number greater than 5, for example: type 6 for X and Y on row 1, type 7 for X and Y on row 2;
1) plot the 2d graph (line, scatter, bars, etc);
1) note that the X and Y axes obviously start at 6 and end at 7;
1) save in the AlphaPlot project format (aproj);
1) close and open the saved file;
1) note that the X and Y axes were automatically resized and now starts at 5 and ends at 7.

I made some changes to fix these behaviors when loading an aproj file (certainly the code I changed can be improved).

In addition, I have enabled autoformatting of the saved file. The advantage is that the file format is human-readable when opened in a text editor. It is also possible to do a better debug, as qDebug messages appear in line and column, while without formatting only the error column appears, since it contains a single line. The disadvantage is that the file is about 10 to 20% larger. However, I think the saved files are relatively small and it wouldn't make much difference.

2020-10-19 15:20 UTC, narunlifescience requested changes

2020-10-20 15:15 UTC, filipestevao commented on alphaplot/src/core/AprojHandler.cpp
> +  xmlwriter->setAutoFormattingIndent(2);
You are right, users will not care whether the saved file is formatted or not. The file size is perhaps more important in this case.

2020-10-20 15:15 UTC, filipestevao commented on alphaplot/src/ApplicationWindow.cpp
> +  /*if (!was_maximized_) {
Old code removed.

2020-10-20 15:39 UTC, narunlifescience approved these changes
:+1:

2020-10-20 15:40 UTC, merged